SELECT CONCAT(COALESCE(ZI."Zone",'Unknown'), ' / ', COALESCE(ZF."Zone", 'Unknown')) AS PAIR,
	AVG(T.TOTAL_AMOUNT) AS MEAN_AMOUNT
FROM YELLOW_TAXI_TRIPS T
LEFT JOIN ZONES ZI ON ZI."LocationID" = T."PULocationID"
LEFT JOIN ZONES ZF ON ZF."LocationID" = T."DOLocationID"
GROUP BY ZI."Zone",
	ZF."Zone"
ORDER BY 2 DESC
LIMIT 1